
var gyms = {
    'ÁCCURA Bruc':'Eixample',
    'ALTAFIT DIAGONAL':'Eixample',
    'BCN-FITNESS':'Eixample',
    'CEM SAGRADA FAMÍLIA':'Eixample',
    'CROSSFIT EIXAMPLE':'Eixample',
    'DIR Claris':'Eixample',
    'DIR Eixample':'Eixample',
    'DUET FIT BRUC':'Eixample',
    'DUET FIT GRAN VIA':'Eixample',
    'EIXAMPLE FITNESS':'Eixample',
    'ESPORTIU ROCAFORT':'Eixample',
    'EUROFITNESS AIGUAJOC':'Eixample',
    'EUROFITNESS SANT MIQUEL':'Eixample',
    'FISIC BARCELONA':'Eixample',
    'FITT BARCELONA':'Eixample',
    'GIMNASIO CURVES Llançà':'Eixample',
    'GIMNASIO CURVES Sagrada Familia':'Eixample',
    'GIMNASIOS EIXAMPLE':'Eixample',
    'GYROTONIC BARCELONA CENTER':'Eixample',
    'HOLMES PLACE Balmes':'Eixample',
    'HOLMES PLACE Urquinaona':'Eixample',
    'LIFESTYLE CONCEPT Barcelona':'Eixample',
    'MAYAN LUXURY SPA':'Eixample',
    'METROPOLITAN Las Arenas':'Eixample',
    'METROPOLITAN Sagrada Familia':'Eixample',
    'NEW BODY BCN':'Eixample',
    'REBODY':'Eixample',
    'REEBOOK CROSSFIT BCN':'Eixample',
    'SALUD Y FORMA':'Eixample',
    'Seven DIR':'Eixample',
    'VITA LIBERTE Plaza Espanya':'Eixample',
    'WELLNESS 33':'Eixample',
    'YOGABODY FITNESS':'Eixample',
    'CEM CAN RICART':'Ciutat Vella',
    'CEM FRONTÓ COLOM':'Ciutat Vella',
    'CEM MARÍTIM':'Ciutat Vella',
    'CLUB NATACIÓ ATLÈTIC BARCELONETA':'Ciutat Vella',
    'CLUB NATACIÓ BARCELONA':'Ciutat Vella',
    'SANT PAU SPORT CLUB':'Ciutat Vella',
    'SWEAT GYM BLISS SPA ':'Ciutat Vella',
    'UFEC ESTACIO DEL NORD':'Ciutat Vella',
    'CEM CLAROR':'Gracia',
    'DIR Gràcia':'Gracia',
    'DON GIMNAS':'Gracia',
    'ESPORTIU CLARET':'Gracia',
    'EUROFITNESS PERILL':'Gracia',
    'GIMNASIO ARSENAL':'Gracia',
    'HOLMES PLACE EUROPOLIS Sardenya':'Gracia',
    'MB COACHING SPORT':'Gracia',
    'METROPOLITAN Balmes':'Gracia',
    'ANYTIME FITNESS CIUTADELLA':'Sant Marti',
    'ANYTIME FITNESS POBLENOU':'Sant Marti',
    'CEM BAC DE RODA':'Sant Marti',
    'CEM CAN FELIPA':'Sant Marti',
    'CEM JÚPITER':'Sant Marti',
    'CEM MARESME':'Sant Marti',
    'CEM VERNEDA':'Sant Marti',
    'CEM VINTRÓ':'Sant Marti',
    'CROSSFIT GALA':'Sant Marti',
    'CROSSFIT POBLENOU':'Sant Marti',
    'FITNESS CLUB BARCELONA':'Sant Marti',
    'MERCURY SPORT CLUB':'Sant Marti',
    'NOVA ICÀRIA Esports Club':'Sant Marti',
    'PALEO BARCELONA':'Sant Marti',
    'SANOAKTIV':'Sant Marti',
    'SIMPLY GYM':'Sant Marti',
    'ANYTIME FITNESS Barcelona':'Sarria-Sant Gervasi',
    'ANYTIME FITNESS SARRIA':'Sarria-Sant Gervasi',
    'ARENA SPORT':'Sarria-Sant Gervasi',
    'ARSENAL Femenino':'Sarria-Sant Gervasi',
    'ARSENAL Masculino':'Sarria-Sant Gervasi',
    'BE YOU WOMAN':'Sarria-Sant Gervasi',
    'BONASPORT':'Sarria-Sant Gervasi',
    'CEM CAN CARALLEU':'Sarria-Sant Gervasi',
    'CENTRE FITNESS SARRIA':'Sarria-Sant Gervasi',
    'CENTRO PILAR DOMINGUEZ':'Sarria-Sant Gervasi',
    'CLINICA DEPORTIVA IANES':'Sarria-Sant Gervasi',
    'DINAMIC':'Sarria-Sant Gervasi',
    'DIR Diagonal':'Sarria-Sant Gervasi',
    'DIR Tres Torres':'Sarria-Sant Gervasi',
    'DIR Tuset':'Sarria-Sant Gervasi',
    'DIR UP and DOWN':'Sarria-Sant Gervasi',
    'DOJO SANT GERVASI':'Sarria-Sant Gervasi',
    'DUET FIT VIA AUGUSTA':'Sarria-Sant Gervasi',
    'FAST FITNESS':'Sarria-Sant Gervasi',
    'FESS LA SALLE':'Sarria-Sant Gervasi',
    'FIFTYFIVE TRAINING CENTER':'Sarria-Sant Gervasi',
    'FITNESS LLEURE':'Sarria-Sant Gervasi',
    'GIMNÀS SARRIÀ':'Sarria-Sant Gervasi',
    'GIMNASIO FEMENINO LINEA':'Sarria-Sant Gervasi',
    'IN 20 MINUTES':'Sarria-Sant Gervasi',
    'INVICTUS WORKOUT':'Sarria-Sant Gervasi',
    'IQ FITNESS':'Sarria-Sant Gervasi',
    'IRADIER CLUB MUJER':'Sarria-Sant Gervasi',
    'KIESER TRAINING Barcelona':'Sarria-Sant Gervasi',
    'KNOCK DOWN Barcelona':'Sarria-Sant Gervasi',
    'LA SALA MAGALI':'Sarria-Sant Gervasi',
    'METROPOLITAN IRADIER':'Sarria-Sant Gervasi',
    'NUUM':'Sarria-Sant Gervasi',
    'NYTTA':'Sarria-Sant Gervasi',
    'O2 CENTRO WELLNESS':'Sarria-Sant Gervasi',
    'PISCINES SANTALO':'Sarria-Sant Gervasi',
    'POLIESPORTIU LA SALLE':'Sarria-Sant Gervasi',
    'PROTRAINING CENTER':'Sarria-Sant Gervasi',
    'PUTXET SPORT':'Sarria-Sant Gervasi',
    'R.C.TENIS BARCELONA 1899':'Sarria-Sant Gervasi',
    'SIAUNCUERPOSANO':'Sarria-Sant Gervasi',
    'SPORT FEMENI BALMES':'Sarria-Sant Gervasi',
    'WATERBIKE BARCELONA':'Sarria-Sant Gervasi',
    'WELL CENTRO':'Sarria-Sant Gervasi',
    'You´re 10':'Sarria-Sant Gervasi',
    'C.E.LAIETA':'Les Corts',
    'CITY SPORT':'Les Corts',
    'CROSSFIT DIAGONAL':'Les Corts',
    'DIR Av.Madrid':'Les Corts',
    'DIR Campus':'Les Corts',
    'ESPORTIU BADRENA':'Les Corts',
    'GIMNAS UPC':'Les Corts',
    'GIMNASIO CURVES Barcelona':'Les Corts',
    'GYM LAIETA':'Les Corts',
    'HOLMES PLACE EUROPOLIS Les Corts':'Les Corts',
    'McFIT Les Corts':'Les Corts',
    'METROPOLITAN Galileo':'Les Corts',
    'ATLES ESPORTS LA BORDETA':'Sants-Montjuic',
    'CEM ESPANYA INDUSTRIAL':'Sants-Montjuic',
    'CLUB ESPORTIU MEDITERRANI':'Sants-Montjuic',
    'CLUB NATACIÓ MONTJUÏC':'Sants-Montjuic',
    'DIR Tarragona':'Sants-Montjuic',
    'FITNESS PLACE':'Sants-Montjuic',
    'FITNESS SANTS':'Sants-Montjuic',
    'GYM BARCELONA SANTS':'Sants-Montjuic',
    'GYM FIRA':'Sants-Montjuic',
    'GYM WORLD TRADE CENTER':'Sants-Montjuic',
    'PISCINAS PICORNELL':'Sants-Montjuic',
    'TENIS POMPEIA':'Sants-Montjuic',
    'WELLNESS POINT':'Sants-Montjuic',
    'ACCENTENNIS BARCELONA':'Horta-Guinardó',
    'CEM MUNDET':'Horta-Guinardó',
    'CLUB ESPORTIU HISPANO FRANCES':'Horta-Guinardó',
    'CONDAL CROSSFIT':'Horta-Guinardó',
    'DIR Castillejos':'Horta-Guinardó',
    'DIR Claret':'Horta-Guinardó',
    'DIR Club Hispà':'Horta-Guinardó',
    'EUROFITNESS HORTA':'Horta-Guinardó',
    'HORTA ESPORTIVA':'Horta-Guinardó',
    'NICK SPA':'Horta-Guinardó',
    'VALL PARC':'Horta-Guinardó',
    'WHU SHU OLIMPO':'Horta-Guinardó',
    'CEM BON PASTOR':'Sant Andreu',
    'DIR Maragall':'Sant Andreu',
    'FITNESS FACTORY CLUB ':'Sant Andreu',
    'GIMNASIO 30 MINUTOS Sant Andreu':'Sant Andreu',
    'McFIT BARCELONA CLOT':'Sant Andreu',
    'VIVA GYM Meridiana':'Sant Andreu',
    'YAWARA GIMNASIO':'Sant Andreu',
    'CEM Cotxeres Borbó':'Nou Barris',
    'CEM TRINITAT VELLA':'Nou Barris',
    'EUROFITNESS ARTESANIA':'Nou Barris',
    'EUROFITNESS CAN CUYÀS':'Nou Barris',
    'EUROFITNESS CAN DRAGÓ':'Nou Barris',
    'GIMNÀS ESPORTS FABRA':'Nou Barris',
    'VIRGIN ACTIVE Can Dragó':'Nou Barris'
};



function authHandler(error, authData) {
    if (error) {
      console.log("Login Failed!", error);
    } else {
      console.log("Authenticated successfully with payload:", authData);
    }

    for(var key in gyms) {
        db.push({name: key, area: gyms[key]});
    }
}

var db = new Firebase('https://fitners.firebaseio.com/gyms/');

var password = window.prompt("Introduce password:","");

db.authWithPassword({
    email    : 'pabloromanh@gmail.com',
    password : password
}, authHandler);
